// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Documentation Tab (User Guides):
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'ARP 系统',
      link: {
        type: 'generated-index',
        description: 'ARP (Anugerah Remaja Perdana) 系统的完整用户使用指南与管理说明。'
      },
      items: [{type: 'autogenerated', dirName: 'arp'}],
    },
    // Example for adding other new modules/subsystems:
    // {
    //   type: 'category',
    //   label: '活动管理系统',
    //   items: [{type: 'autogenerated', dirName: 'events'}],
    // }
  ],

  // Dev Notes Tab (Developer Documentation): Autogenerates all developer subfolders inside dev-notes/
  devNotesSidebar: [
    {
      type: 'autogenerated',
      dirName: 'dev-notes',
    }
  ],
};

export default sidebars;
