// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Documentation Tab (User Guides):
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'ARP 系统',
      link: {
        type: 'generated-index',
        description: 'ARP (Anugerah Remaja Perdana) 系统的完整用户使用指南与管理说明。'
      },
      items: [{type: 'autogenerated', dirName: 'arp'}],
    },
    {
      type: 'category',
      label: '精英团系统',
      link: {
        type: 'generated-index',
        description: '蒲公英精英团干部委任、年度配置、Excel批量导入与委任状/委任函管理指南。'
      },
      items: [{type: 'autogenerated', dirName: 'ma'}],
    },
  ],

  // Dev Notes Tab (Developer Documentation): Autogenerates all developer subfolders inside dev-notes/
  devNotesSidebar: [
    {
      type: 'autogenerated',
      dirName: 'dev-notes',
    }
  ],
};

export default sidebars;
